name: JSDoc Generation

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Get Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure Node.js
      run: |
        npm install
        npm install -g jsdoc

    - name: Generate Documentation
      run: jsdoc -c ./source/jsdoc.conf.json

    - name: Push to Repo
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'Automatic Documentation Update'
        add: '.'
