name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      - with:
          node-version: ${{ matrix.node-version }}
      - run: |
          working-directory: ./source
          npm install
          npm run build --if-present
          npm test

  lint:
      runs-on: ubuntu-latest
          
      steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./source
        run: npm install
      - name: Run ESLint
        working-directory: ./source
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --ignore-pattern "jsdocs/**"
